set encoding=utf-8
set fileencodings=ucs-bom,utf-8,gbk,big5,latin1
colorscheme desert           " 代码高亮主题
syntax enable                " 打开语法高亮
syntax on                    " 开启文件类型侦测
set noerrorbells             " 关闭提示音
set nocompatible             " 关闭兼容模式
set nobackup                 " 取消自动备份
set tabstop=4                " 设置tab键的宽度
set softtabstop=4            " 使得按退格键时可以一次删掉4个空格
set expandtab                " 将tab转换为4个空格
set shiftwidth=4             " 换行时行间交错使用4个空格
set backspace=2              " 设置退格键可用
set cindent shiftwidth=4     " 自动缩进4空格
set smartindent              " 智能自动缩进
set autoindent               " 设置自动缩进
set number                   " 显示行号
set ruler                    " 右下角显示光标位置的状态行
set incsearch                " 查找book时，当输入/b时会自动找到
set hlsearch                 " 开启高亮显示结果
set incsearch                " 开启实时搜索功能
set nowrapscan               " 搜索到文件两端时不重新搜索
set ignorecase               " 搜索时忽略大小写
set autochdir                " 设定文件浏览器目录为当前目录
set showcmd                  " 显示正在输入的命令
set wildmenu                 " 在命令模式下使用Tab自动补全时，显示一个漂亮的单行菜单
set foldmethod=syntax        " 折叠代码
set foldlevel=100            " 文件打开时不折叠
set history=20               " 设置命令历史列表的长度
set pastetoggle=<F9>         " 设置粘贴模式的快捷键
set list                     " 显示非可见字符
set listchars=tab:>-,trail:- " 设置非可见字符的显示模式
filetype plugin indent on    " 为特定文件类型加载对应的插件以及加载相关缩进文件
" 自定义函数
func! RTrim()
    %s/\s\+$//ge
endfunc
" 代码折叠
map <F2> zM
imap <F2> <ESC> zM
vmap <F2> <ESC> zM
map <F3> zR
imap <F3> <ESC> zR
vmap <F3> <ESC> zR
" 去除行尾空格
autocmd BufWritePre * :call RTrim()
" 代码补全
imap <c-g> <c-x><c-u>
" 设置全能补全
autocmd FileType ruby,eruby set completefunc=rubycomplete#Complete
autocmd FileType python set completefunc=pythoncomplete#Complete
autocmd FileType javascript set completefunc=javascriptcomplete#CompleteJS
autocmd FileType html set completefunc=htmlcomplete#CompleteTags
autocmd FileType css set completefunc=csscomplete#CompleteCSS
autocmd FileType xml set completefunc=xmlcomplete#CompleteTags
autocmd FileType java set completefunc=javacomplete#Complete
